/**
 * Server-only loader for Confluence — the daily MTG connections puzzle.
 *
 * Source of truth is `data/connections/puzzles.json`, generated by
 * `node scripts/build-connections.mjs` (house static-data pattern:
 * bundled JSON import, zero runtime API calls). Hand-authored boards
 * in `data/connections/curated.json` override the generated rotation
 * for specific UTC dates.
 *
 * IMPORTANT: never import this module from a client component — the
 * puzzles file carries every answer (and ~600KB of them). The daily
 * page passes a single puzzle down as a prop, and endless mode pulls
 * one at a time through /api/confluence/puzzle.
 */

import puzzlesJson from "../data/connections/puzzles.json";
import curatedJson from "../data/connections/curated.json";

export interface ConnectionsCard {
  name: string;
  set: string;
  cn: string;
  /** Scryfall art_crop URL — solved-row thumbnails. */
  art: string;
  /** Scryfall `normal` JPEG — full-card popup. */
  img: string;
}

export interface ConnectionsGroup {
  /** Generator's instance key (e.g. "artist:John Avon"). Absent on
   *  hand-authored boards; informational only. */
  key?: string;
  title: string;
  /** 0 yellow (easiest) → 3 purple (trickiest). Drives tile colors
   *  and the share-grid emoji. */
  difficulty: 0 | 1 | 2 | 3;
  cards: ConnectionsCard[];
}

export interface ConnectionsPuzzle {
  id: string;
  /** True when all 16 cards are available in a recent premier set
   *  (see RECENT_MONTHS in the generator). Backs the endless-mode
   *  "newer sets" filter; absent on catalog-wide boards. */
  recent?: boolean;
  groups: ConnectionsGroup[];
}

interface PuzzleFile {
  _doc?: string;
  generatedAt?: string;
  seed?: number;
  /** UTC date of puzzle #1. */
  epoch: string;
  puzzles: ConnectionsPuzzle[];
}

interface CuratedFile {
  _doc?: string;
  byDate?: Record<string, ConnectionsPuzzle>;
}

const FILE = puzzlesJson as unknown as PuzzleFile;
const CURATED = curatedJson as unknown as CuratedFile;

/** Today's key in UTC (YYYY-MM-DD). The daily flips at UTC midnight for
 *  everyone — one shared board is the whole point of a daily. */
export function todayUtcDate(): string {
  return new Date().toISOString().slice(0, 10);
}

function daysBetweenUtc(fromIso: string, toIso: string): number {
  const from = Date.parse(`${fromIso}T00:00:00Z`);
  const to = Date.parse(`${toIso}T00:00:00Z`);
  return Math.floor((to - from) / 86_400_000);
}

/** Light shape check so a typo in hand-edited curated.json degrades to
 *  the generated rotation instead of crashing the page. */
function isValidPuzzle(p: unknown): p is ConnectionsPuzzle {
  if (!p || typeof p !== "object") return false;
  const groups = (p as ConnectionsPuzzle).groups;
  if (!Array.isArray(groups) || groups.length !== 4) return false;
  return groups.every(
    (g) =>
      g &&
      typeof g.title === "string" &&
      Array.isArray(g.cards) &&
      g.cards.length === 4 &&
      g.cards.every((c) => c && typeof c.name === "string"),
  );
}

/**
 * The daily board for a UTC date, plus its display number ("Confluence
 * #N", 1-based from the epoch). Dates before the epoch clamp to #1.
 * The generated pool wraps around when exhausted; curated overrides
 * win outright for their date.
 */
export function getDailyPuzzle(dateUtc: string): {
  puzzle: ConnectionsPuzzle;
  number: number;
} {
  const dayIndex = Math.max(0, daysBetweenUtc(FILE.epoch, dateUtc));
  const number = dayIndex + 1;

  const curated = CURATED.byDate?.[dateUtc];
  if (curated && isValidPuzzle(curated)) {
    return { puzzle: normalize(curated), number };
  }

  const pool = FILE.puzzles;
  return { puzzle: normalize(pool[dayIndex % pool.length]), number };
}

/** A random board for endless mode. `excludeId` keeps the daily (or
 *  the board just played) from repeating back-to-back; `recentOnly`
 *  restricts to boards built from the recent premier window. Filters
 *  relax in order (drop exclude, then drop recent) rather than ever
 *  failing — a pool generated offline has no recent tags at all. */
export function getRandomPuzzle(
  excludeId?: string,
  opts?: { recentOnly?: boolean },
): ConnectionsPuzzle {
  const pool = FILE.puzzles;
  const recentPool = opts?.recentOnly ? pool.filter((p) => p.recent) : pool;
  const base = recentPool.length > 0 ? recentPool : pool;
  const eligible = excludeId ? base.filter((p) => p.id !== excludeId) : base;
  const list = eligible.length > 0 ? eligible : base;
  return normalize(list[Math.floor(Math.random() * list.length)]);
}

/** Groups sorted by difficulty so clients can rely on the order, and
 *  difficulty coerced onto the 0–3 scale (curated files are hand-typed). */
function normalize(p: ConnectionsPuzzle): ConnectionsPuzzle {
  return {
    id: p.id,
    ...(p.recent ? { recent: true } : {}),
    groups: [...p.groups]
      .sort((a, b) => a.difficulty - b.difficulty)
      .map((g, i) => ({
        ...g,
        difficulty: (Math.min(3, Math.max(0, Number(g.difficulty ?? i))) | 0) as 0 | 1 | 2 | 3,
      })),
  };
}
