/**
 * Static lookup for per-set art-crop URLs + artist credits.
 *
 * Source of truth is `data/set-art.json`, generated by running
 * `node scripts/build-set-art.mjs`. Each entry shape is
 * `{ url, artist, cardName }` — the URL drives the visual, and the
 * artist/cardName fields back the "Art by <X>" credits we surface
 * on every art-crop surface (homepage CTA cards, set tiles, per-set
 * hero, single-card popups).
 *
 * Imported via static JSON so the data is bundled at build time —
 * pages render with zero live Scryfall calls and no Vercel timeout
 * risk on cold starts.
 */

import setArtJson from "../data/set-art.json";

/** A single set's cached art credit. `url` is always present for
 *  cached sets; artist + cardName can be null on sets the build
 *  script couldn't credit (rare — usually pre-1996 sets without
 *  consolidated artist metadata on Scryfall). */
export interface SetArtEntry {
  url: string;
  artist: string | null;
  cardName: string | null;
}

interface SetArtFile {
  _doc?: string;
  generatedAt?: string;
  setCount?: number;
  // Legacy entries (pre-enrichment build) were plain URL strings.
  // The current build script migrates them to the object shape on
  // next run, but we accept the union here so a stale file doesn't
  // crash the type-checker.
  art: Record<string, SetArtEntry | string>;
}

const FILE = setArtJson as SetArtFile;

function normalize(v: SetArtEntry | string | undefined): SetArtEntry | undefined {
  if (!v) return undefined;
  if (typeof v === "string") return { url: v, artist: null, cardName: null };
  return v;
}

/** Lowercased set-code → full art entry map (url + artist + cardName).
 *  Use this when you need the credit; for "just the URL", call
 *  `getSetArtUrlMap()` so consumers don't have to dereference `.url`. */
export function getSetArtMap(): Record<string, SetArtEntry> {
  const out: Record<string, SetArtEntry> = {};
  for (const [code, v] of Object.entries(FILE.art ?? {})) {
    const norm = normalize(v);
    if (norm) out[code.toLowerCase()] = norm;
  }
  return out;
}

/** Backwards-compatible URL-only view of the art map. Callers that
 *  only paint the image (no credit needed) can keep using this. */
export function getSetArtUrlMap(): Record<string, string> {
  const map = getSetArtMap();
  const out: Record<string, string> = {};
  for (const [code, entry] of Object.entries(map)) {
    out[code] = entry.url;
  }
  return out;
}

/** Single-set lookup, full entry. Returns undefined when uncached. */
export function getSetArt(setCode: string | undefined): SetArtEntry | undefined {
  if (!setCode) return undefined;
  return getSetArtMap()[setCode.toLowerCase()];
}

/** Single-set URL lookup. Convenience for old call sites; new code
 *  should prefer `getSetArt()` so it can also surface the credit. */
export function getSetArtUrl(setCode: string | undefined): string | undefined {
  return getSetArt(setCode)?.url;
}
