/**
 * Static lookup for per-set art-crop URLs.
 *
 * Source of truth is `data/set-art.json`, generated by running
 * `node scripts/build-set-art.mjs`. The set-picker pages call
 * `getSetArtMap()` to get every URL we already know, then optionally
 * fall back to `getSetSampleArt` for any set that isn't in the JSON
 * yet (e.g. a brand-new release added since the last script run).
 *
 * Imported via static JSON so the URLs are bundled at build time —
 * pages render with zero live Scryfall calls and no Vercel timeout
 * risk on cold starts.
 */

import setArtJson from "../data/set-art.json";

interface SetArtFile {
  _doc?: string;
  generatedAt?: string;
  setCount?: number;
  art: Record<string, string>;
}

const FILE = setArtJson as SetArtFile;

/** Lowercased set-code → art_crop URL map. */
export function getSetArtMap(): Record<string, string> {
  return FILE.art ?? {};
}

/** Single-set lookup. Returns undefined if not cached. */
export function getSetArt(setCode: string | undefined): string | undefined {
  if (!setCode) return undefined;
  return getSetArtMap()[setCode.toLowerCase()];
}
